### ISSUE TITLE
I can't register sciter's new forum.

### ISSUE THREAD

**Issue by gxlmyacc** [c-smile/sciter-sdk#1]
Hi, Andrew. 
I can&#39;t register sciter&#39;s new forum. because I don&#39;t receive email notifications after the registration. I want to get a new password, but the site tips:
   The e-mail could not be sent.
   Possible reason: your host may have disabled the mail() function.

now, I have a new problem, see this demo:

myStyle.css:
[code]
   @set myStyle {
      div:root {
        background-color: red;
      }
    }

    div {
      style-set: myStyle;
    }
[/code]
main.html:
[code]
&lt;html&gt;
 &lt;head&gt;
  &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;myStyle.css&quot; /&gt;
  &lt;style type=&quot;text\css&quot;&gt;
    div {
      width: 100;
      height: 100;
      background-color: green;
    }
  &lt;/style&gt;
 &lt;/head&gt;
 &lt;body style=&quot;&quot;&gt;
   &lt;div&gt;ssssdfsdf&lt;/div&gt;
 &lt;/body&gt;
&lt;/html&gt;
[/code]
You will see the color of div be red. it&#39;s not green

**Comment by gxlmyacc** [comment]
Hi, Andrew. 
I can&#39;t register sciter&#39;s new forum. because I don&#39;t receive email notifications after the registration. I want to get a new password, but the site tips:
   The e-mail could not be sent.
   Possible reason: your host may have disabled the mail() function.

now, I have a new problem, see this demo:

myStyle.css:
[code]
   @set myStyle {
      div:root {
        background-color: red;
      }
    }

    div {
      style-set: myStyle;
    }
[/code]
main.html:
[code]
&lt;html&gt;
 &lt;head&gt;
  &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;myStyle.css&quot; /&gt;
  &lt;style type=&quot;text\css&quot;&gt;
    div {
      width: 100;
      height: 100;
      background-color: green;
    }
  &lt;/style&gt;
 &lt;/head&gt;
 &lt;body style=&quot;&quot;&gt;
   &lt;div&gt;ssssdfsdf&lt;/div&gt;
 &lt;/body&gt;
&lt;/html&gt;
[/code]
You can see the color of div is red. it&#39;s not green

**Comment by pravic** [comment]
`style-set` has higher priority in css specification rules. Check [CSS extensions in h-smile engine](http://www.terrainformatica.com/2007/04/css-extensions-in-h-smile-engine-part-i-style-sets/)
 and [Style sets in H-SMILE core](http://www.terrainformatica.com/2010/09/style-sets-in-h-smile-core/).

**Comment by gxlmyacc** [comment]
I know this, but I think it's not a good deal, which means I can't cover the style-set in other places.

**Comment by c-smile** [comment]
You can override values defined in style sets by using !important modifier.

**Comment by gxlmyacc** [comment]
Well, it seems the only way. Thanks.

**Comment by gxlmyacc** [comment]
Hi,  Andrew. Can sciter support this definition? I think this code will be more pretty:
&lt;html&gt;
 &lt;head&gt;
  &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;myStyle.css&quot; /&gt;
  &lt;style type=&quot;text\css&quot;&gt;
   @set myStyle-custom &lt; myStyle {
     :root {
       background-color: green;
     }
    }
    div {
      width: 100px;
      height: 100px;
      style-set: myStyle-custom;
    }
  &lt;/style&gt;
 &lt;/head&gt;
 &lt;body style=&quot;&quot;&gt;
   &lt;div&gt;ssssdfsdf&lt;/div&gt;
 &lt;/body&gt;
&lt;/html&gt;
