### ISSUE TITLE
Bug in XP os(4.2.6.8):

### ISSUE THREAD

**Issue by Nasiri63** [c-smile/sciter-sdk#100]
Hi,
I have a problem in new version of sciter(4.2.6.8) in XP os.
I have this css in my code.
ul.classzone > li:expanded {
    height: max-content;
    transition: height(sine-in-out, 400ms);
}
There was no problem in older version(4.2.5.X) but in new version I had to comment "transition: height" because this line keep li closed.

**Comment by c-smile** [comment]
I've answered on this here: https://sciter.com/forums/topic/bug-on-xp-os4-2-6-8/
