### ISSUE TITLE
very good project, is it free to use?

### ISSUE THREAD

**Issue by lucpp** [c-smile/sciter-sdk#101]

**Comment by c-smile** [comment]
Yes, you can use for free bin/32/sciter.dll or bin/64/sciter.dll (Windows), sciter-osx-64.dylib (OS X) and sciter-gtk-64.so (Linux) as they are published on the site in public SDK release. You are allowed to use them according to terms of license.htm included in public SDK distribution.

Paid options are for the cases when you need to access Sciter source code (e.g. to be able to link Sciter statically into your application) and to receive guarantied technical support. 

Check https://sciter.com/prices/

**Comment by lucpp** [comment]
thanks
