### ISSUE TITLE
sciter could not load img(relative path) since 4.2.6.5 on win10 rust-sciter binding

### ISSUE THREAD

**Issue by woodgear** [c-smile/sciter-sdk#102]
os win10
binging rust-sciter-0.5.45
how i test: change sciter.dll under current dir

same code under 4.2.6.5 could load img under 4.2.6.6 not
if you want i could send to my demo
4.2.6.6 log
```log
WARNING:DOM: failed to load "//rust.png" file, error=161
WARNING:DOM: failed to load "//./rust.png" file, error=2
```

**Comment by wxiaoguang** [comment]
Please read the sciter's log: 4.2.6.6: `support of file://winsharename/path and file:///winsharename/path URLs on Windows.`

A path starting with "//" is a UNC path here.

You should avoid it if you do not know what you are doing.

Use `C:/rust.png` or `./rust.png` to access your file.

**Comment by woodgear** [comment]
i used like above
```
<html>
<body>
<img src="rust.png">
<img src="./rust.png">
<img src=".\rust.png">

</body>
</html>
```
and all failed

**Comment by woodgear** [comment]
thanks a lot. when i use absolute path to load root document it works as normal.
i think that will be a break change  i just dnot realize
