### ISSUE TITLE
Question about @image-map

### ISSUE THREAD

**Issue by Nathan1852** [c-smile/sciter-sdk#103]
I have a question about using image-map with an image that is rebuilt on the server side.
How would I recreate the map item names when the image is changing, for example when a new Icon is added while the program is running?

Edit: The best way is probably to use Tiscript and the graphics api instead

**Comment by c-smile** [comment]
Not clear what you want to achieve so some task definition is needed.

Otherwise you can recreate/reload CSS containing that image-map but I suspect there are better options.

**Comment by Nathan1852** [comment]
Reload could be an option, but I'll probably just use the graphics api on an element instead.
Thank you for the info
