### ISSUE TITLE
how to dynamic change title (use tiscript)?

### ISSUE THREAD

**Issue by woodgear** [c-smile/sciter-sdk#109]

**Comment by c-smile** [comment]
title attribute or title of a window?

If window's title then 
```
view.windowTitle = "new title";
```

**Comment by pravic** [comment]
[`view.windowCaption`](https://sciter.com/docs/content/sciter/View.htm)?

**Comment by open-trade** [comment]
> [`view.windowCaption`](https://sciter.com/docs/content/sciter/View.htm)?

this works

**Comment by c-smile** [comment]
> on mac
```
view.windowCaption = ...; 
```
on Mac too. But it does matter when you call this function. It will work only after window initialization. Here it will work:
```
function self.ready() {
  view.windowCaption = "Hello world";
}
```
