### ISSUE TITLE
Certain special characters in file path do not work

### ISSUE THREAD

**Issue by SonnyX** [c-smile/sciter-sdk#115]
Loading files where the absolute path contains characters such as '#' will cause sciter to not being able to find the file.
Can be verified by placing a .htm file inside of a folder that starts with '#' and trying to load it using usciter.
(this affects at least both windows and Linux)

**Comment by c-smile** [comment]
SciterLoadFile() expects URL of file. And '#' in URLs have special meaning - name of location to scroll to. 

If file path contains non-safe URL characters it shall be url-escaped, 
instead of `file:///folder#/file.htm`  it shall look like as `file:///folder%23/file.htm`

Check:

**Comment by SonnyX** [comment]
Although that works for loading up the file, any files loaded from that file using a **relative** path fail due to the same reason where the relative path does not contain special characters.

**Comment by SonnyX** [comment]
tried again on newer versions of sciter and seems to be working now
