### ISSUE TITLE
css float crashing sciter

### ISSUE THREAD

**Issue by UnnoTed** [c-smile/sciter-sdk#12]
when i add the float (at the file: gui/styles/header/navbar.css line: 19 or 23) and click the "hud" button, it makes sciter crash.

it is a really simple code:

https://dl.dropboxusercontent.com/u/15029339/sciter_float_bug.zip

**Comment by c-smile** [comment]
I do not see any crash with latest version (3.3.1.2).
Any details? OS, version, etc.

**Comment by UnnoTed** [comment]
win10 x64
it's being caused by load()

i tried to make a small "mvc without model" by using load() to insert the html into an element, but element selectors in tiscript would give error saying the element wasn't found (on each controller) then i used load() to read the controller from a file when the view was called, it worked fine until i added the float property on the css file.

i'll find another way to do so.
