### ISSUE TITLE
Windows XP some issues

### ISSUE THREAD

**Issue by xiaoliang314** [c-smile/sciter-sdk#125]
This project is great, I used it to develop some very cool apps.
But it doesn't work very well on Windows XP. Here are some of my issues:
1. The window background color is set to a radial-gradient display is not normal, example: 
```
html {
    background: radial-gradient(50% 0%, 300vw 300vh, #1b2947 10%, #75517d 40%, #e96f92 65%, #f7f7b6);
}
```
2. Plaintext element does not display tab characters properly, example: samples/ideas/ide

Last issue, I can't register your forum, I use Tecent QQ-email, the website prompts that I can't send mail.

**Comment by c-smile** [comment]
Instead of using sciter.dll from /bin/32 folder try dll from /bin/skia32

/bin/32/sciter.dll uses GDI+ backend on XP and GDI+ is too old for anything useful.
/bin/skia32/sciter.dll uses Skia for rendering on XP - it is way better.

"QQ-email" can really be used only inside China.  Create account on gmail/hotmail/outlook if you want to talk with outside world. 

Try this phrase: "Problems delivering mail to QQ" in your search engine and you will get an idea why.

**Comment by xiaoliang314** [comment]
@c-smile Thank you very much, your reply is very useful. I believe now, the sciter is very mature, but sometimes I don’t know how to use it.

**Comment by xiaoliang314** [comment]
@c-smile Hi Andrew, skia does not seem to support Chinese. 
The following is the test text:
```
中文文字测试，中文文字测试。
```
In addition, plaintext element does not support two commonly used symbols in Chinese, this issue exists in all versions, which are:
```
，。
```

**Comment by c-smile** [comment]
It does support it. You just need to list fonts that has these symbols.
```
html {
   font-family: Tahoma,  "Microsoft YaHei", "SimSun-ExtB", sans-serif; 
}
```
or something like that - whatever full fonts that Chinese Windows XP has.
For font matching I am using Windows supplied services and they have some limitations on XP.

I can add better implementation (with the price of incresing engine size) but XP becomes less and less viable each day, its support does not bring any money to support the effort.

**Comment by xiaoliang314** [comment]
@c-smile I follow your advice, but it seems to have no effect.

**Comment by xiaoliang314** [comment]
@c-smile Sorry, I should apply it on plaintext, it is valid

**Comment by c-smile** [comment]
```
Tahoma,  "Microsoft YaHei", "SimSun-ExtB", sans-serif; 
```
was just an example. You shall provide real font names found on XP.

Yet you should do that for `plaintext` element too. As it uses `font-family:"courier new"` by default and that font may not have all needed symbols.

**Comment by xiaoliang314** [comment]
@c-smile Yes, I am successful, he should be applied separately.

**Comment by xiaoliang314** [comment]
@c-smile I have given up using the radial-gradient feature, and because skia doesn't support Chinese, I can only choose to continue using GDI+. Is there any option to make GDI+ support displaying tab characters?

**Comment by c-smile** [comment]
Could you make your mind? 

Either you "succeeded" or "skia doesn't support Chinese". Whichever is true?

**Comment by xiaoliang314** [comment]
@c-smile No, skia does not support Chinese. After I succeeded in modifying the font, the special symbol can be displayed, It is not skia.

**Comment by c-smile** [comment]
Please provide reproducible sample (HTML)

**Comment by xiaoliang314** [comment]
@c-smile 
This is a Chinese sample that skia does not support, Save as utf-8 with bom.
```
<html>
  <head>
    <style>
    </style>
  </head>
<body>
  <p>这是中文！</p>
</body>
</html>
```
About tab character display issue:
Please use Windows XP to open the spicer-sdk/samples/ideas/ide example. Pressing the tab in ide or loading a file with tabs will reproduce it.

**Comment by c-smile** [comment]
Here is what I see here (XP/SP3 English)

<img src="https://sciter.com/wp-content/uploads/2019/07/xp-chinese.png">

What problem do you see?

**Comment by xiaoliang314** [comment]
@c-smile 
It doesn't seem to support decoding Chinese from a file, but it's normal for me to input Chinese from the edit box.

**Comment by c-smile** [comment]
> It doesn't seem to support decoding Chinese from a file

Sample please.

**Comment by xiaoliang314** [comment]
@c-smile 
![image](https://user-images.githubusercontent.com/37136802/61145154-4c9a9a80-a509-11e9-8342-eb503d8228bd.png)
![image](https://user-images.githubusercontent.com/37136802/61145213-7489fe00-a509-11e9-943c-89c576c95dd4.png)
This is my file:

[test.zip](https://github.com/c-smile/sciter-sdk/files/3387322/test.zip)

**Comment by xiaoliang314** [comment]
@c-smile 
> What problem do you see?

This display is right.
