### ISSUE TITLE
Scrolling in date input field causes negative date

### ISSUE THREAD

**Issue by AshfordN** [c-smile/sciter-sdk#128]
If the date input field contains the default value (00/00/0000), scrolling down in the field (either using the scroll wheel or the down arrow) causes the date to contain negative values. This problem goes a bit further om Linux, by crashing the program.

Below is the minimum code to reproduce the error

```html
<html>
    <body>
        <input type="date" />
    </body>
</html>
```

**Comment by MaherFa** [comment]
I couldn't reproduce this issue on Windows 10 x64.
default date values on my system are `dd / MM / yyyy` I also tried changing date format and had no effect.

**Comment by AshfordN** [comment]
The issue was addresses for Windows in build# 4.3.11

> [<input|date> <input|time>] better handling of undefined (unset) state, shows [yyyy-mm-dd] text by default. 

>
