### ISSUE TITLE
scapp 32-bit crash when using <video> in windows 64-bit

### ISSUE THREAD

**Issue by MaherFa** [c-smile/sciter-sdk#129]
using scapp 32-bit "bin\32\scapp.exe" version 4.3.0.10, on Windows 10 x64

`<video src='video.wmv' />`

scapp will close (crash?) with no error messages

using same project with scapp 64-bit "bin\64\scapp.exe" will work as expected
same results all samples from "samples\video"

**Comment by MaherFa** [comment]
Sadly the issue is still present for me in build# 4.3.0.12.
can I do anything do help debug the issue?

**Comment by c-smile** [comment]
I've just updated it again: https://github.com/c-smile/sciter-sdk/commit/6caeaa1c8417e0eebcdebf1d2f4eb507a3ab5168 

Could you try?

**Comment by MaherFa** [comment]
Sorry for the late reply, different time zone.

**Yes!** the issue is fixed, Thank you so much.
