### ISSUE TITLE
window-blurbehind does not work with scapp 64-bit

### ISSUE THREAD

**Issue by MaherFa** [c-smile/sciter-sdk#130]
**OS:** Windows 10 64-bit

**Sciter SDK:** 4.3.0.11

**Issue:** `window-blurbehind` does not work with scapp 64-bit

**How to reproduce:** run "_\samples\acrylic-window\acrylic-window-sketch.htm_" using "_\bin\64\scapp.exe_"

**More Info:**

- Running same sample using 32-bit version of scapp work as expected.
- `window-frame` have no effect
- issue is present using `window-blurbehind="light"` and `window-blurbehind="dark"`

**Comment by MaherFa** [comment]
**Followup:** `System.OS` returns `Windows-8` when using scapp 64 while the 32 version return the correct value of `windows-10`. could this be the issue?

at the moment the scapp 64 window shows a "tint" over the "accent" color, while removing the `window-blurbehind` causes the window to show a "tint" over the original background color (grey).

**Comment by c-smile** [comment]
Yep, scapp/64bit does not include proper manifest. Fixing.

**Comment by MaherFa** [comment]
Issue resolved with build# 4.3.0.12, Thank You.
