### ISSUE TITLE
Add Release Tags

### ISSUE THREAD

**Issue by tajmone** [c-smile/sciter-sdk#138]
It would be very helpful if each Sciter SDK release commit would be tagged with its version number.

This would allow specific projects (including bindings for other languages) to target a specific version of Sciter and use its release tag to:

- Checkout a specific version in submodules.
- Create scripts to download the SDK binaries of a specific version via cURL.
- Validate a Sciter-based project build via continuous integration services, targeting a specific version.

Currently, to target specific version one needs to know the commit hash of that version, which is not as practical — e.g. to target v4.4.0.1 one would have to refer to commit 0c8fc2d, whereas the `4.4.0.1` tag would me more intuitive and practical.

I realize that there are plenty of releases right now, so you might consider starting to use tag from the current version onward — and maybe also tag the latest Sciter v3 release as well, for legacy projects that depend on it.

Another useful thing would be to provide a means to query the repository (on `master` branch) to know which is the latest SDK release. E.g. by providing a plain text file `version` containing only the version number, which could then be downloaded via rawgit.com and its contents parsed to determine the current versions of the SDK and use that as the tag reference for all Git operations — this would allow to target the specific release, regardless of whether `master` branch is ahead with extra commits.

**Comment by mitsukuri** [comment]
Would be great indeed!
