### ISSUE TITLE
4.4.0.2, no windows x64 scapp, inspector etc

### ISSUE THREAD

**Issue by mitsukuri** [c-smile/sciter-sdk#139]
Hi,
v4.4.0.2 lacks x64 windows versions of `scapp.exe`, `inspector.exe` and other executables that used to be there in the `bin` folder - now there's only `bin.win/x64skia` folder with just two files: `wsciter.exe` and `sciter.dll`..

**Comment by c-smile** [comment]
Thanks. I've added them now. Except of inspector.exe - use x32/inspector.exe .

**Comment by mitsukuri** [comment]
Thank you!
