### ISSUE TITLE
directx samples linked with debug libraries

### ISSUE THREAD

**Issue by pravic** [c-smile/sciter-sdk#15]
sciter-directx.exe requires d3dx11d_43.dll

**Comment by c-smile** [comment]
Yes, it's because of `D3DX11CompileFromFile` and `D3DX11CreateShaderResourceViewFromFile` functions that are in d3dx11d dll. 

That project is a modified version of Microsoft's dxsdk\Samples\C++\Direct3D11\Tutorials\Tutorial07 
I haven't changed their original code.

**Comment by midiway** [comment]
what should I install in order to be able to run it? Is there a DirectX SDK?

**Comment by c-smile** [comment]
Here I think:
https://www.microsoft.com/en-us/download/details.aspx?id=6812

**Comment by midiway** [comment]
yeah, but is it correct/current? it dates from jun 2010..

**Comment by c-smile** [comment]
That is it. DirectX  versions 10 and 11.
