### ISSUE TITLE
about cookie

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [c-smile/sciter-sdk#153]
I have a question to ask.About sciter-sdk ，Does sciter-sdk support cookie?

**Comment by LeiZhang-Hunter** [comment]
I have a question to ask you. Does your software library support cookie?

**Comment by c-smile** [comment]
Sciter preserves server side cookies. But you cannot set them from client side yet. I have plans to add support client side cookies.

**Comment by LeiZhang-Hunter** [comment]
thanks
