### ISSUE TITLE
microformat no longer works

### ISSUE THREAD

**Issue by AshfordN** [c-smile/sciter-sdk#154]
Element.append() and similar functions that use the microformat no longer work, and causes the program to crash.

**Comment by c-smile** [comment]
Microformat works but it is more strict I would say and aligned with the [SSX](https://sciter.com/developers/sciter-docs/reactor-and-ssx/).

So you can use either this:
```
$(body).append([div: {class:"foo"}, ["hello world"]]);
```
or this 
```
$(body).append( <div.foo>hello world</div> );
```
which are technically the same expressions.

**Comment by AshfordN** [comment]
Which format is preferred going forward?

**Comment by AshfordN** [comment]
I'm also having trouble doing the following:

```
//code that defines an array of rows

this.append(
    <table>
        <tbody>{rows}<tbody>
    </table>
)
```

the follow doesn't work either

```
this.append(
    <table>
        <tbody>
            <tr>
                <td>hello world</td>
            </tr>
        </tbody>
    </table>
)
```

the program simply crashes with a segmentation fault

**Comment by c-smile** [comment]
Just use SSX:

```
<html>
    <head>
        <title>Test</title>
        <style>


        </style>
        <script type="text/tiscript">

const data = ["Banana","Appricot","Apple"];

const rows = data.map( fruit => <tr><td>{fruit}</td></tr> );


$(body).append(
    <table border>
        <tbody>{rows}</tbody>
    </table>
);

        </script>
    </head>
    <body>
    </body>
</html>
```

**Comment by AshfordN** [comment]
I've got it working. Thanks for your help.
