### ISSUE TITLE
Hello World Tutorial with mac not work

### ISSUE THREAD

**Issue by ofirrifo** [c-smile/sciter-sdk#155]
I want to run this [Hello World](https://sciter.com/tutorials/hello-world-tutorial/) with mac
in step 2 there is a broken link >> https://github.com/c-smile/sciter-sdk/tree/master/bin/32

1. how to execute the Hello World with mac OS ?
2. Is angular 2 supported ? 

Thanks

**Comment by c-smile** [comment]
Thanks, I've fixed the link.

scapp executable for Mac is here: https://github.com/c-smile/sciter-sdk/tree/master/bin.osx

You may need "chmod" it after copying on you mac. 

> Is angular 2 supported ?

angular 2 was designed to run specifically inside Web browsers.  So it will not run in Sciter.

But Sciter has close feature - the Plus framework : https://github.com/c-smile/sciter-sdk/tree/master/samples/%2Bplus , check /samples there.

But I really suggest to use React[or] https://sciter.com/developers/sciter-docs/reactor-and-ssx/
for many reasons.
