### ISSUE TITLE
window chrome role for window-frame='solid' not working in macOs 10.15.3 with  sciter 4.4.2.4-bis

### ISSUE THREAD

**Issue by mchampaneri** [c-smile/sciter-sdk#156]
window-frame='solid' is working, it makes window with solid background and no titlebar and no controllers.

But chrome roles of window are not working. I am not able to drag window or close window using the window-role elements.

FYI 
I am using go-sciter binding

**Comment by c-smile** [comment]
Version of Sciter and your OS?

Anyway try to run wsciter.exe and in there load /sdk/samples/dialogs+windows/test-window.htm -> "Custom Frame Window". Will you have same problem with that?

**Comment by mchampaneri** [comment]
@c-smile 

Sir,
I go through your example. **You have used window type popup**.  

**_With window type popup it's working. But, with window type main it's not working.  Is that correct behaviour?_**

If yes, then you can close this issue.

Thanks & Regards,
Manish Champaneri

**Comment by c-smile** [comment]
As I said, usciter.app uses custom window frame 

It uses chrome role elements, at least: 
```
<window-caption role=window-caption>&#xb5;Sciter</window-caption>
```
https://github.com/c-smile/sciter-sdk/blob/master/demos/usciter/res/default-osx.htm

Yet, for main window I'd suggest `window-frame='extended'`. Among other things it delegates rendering of standard minimize/maximize buttons to OS:

https://sciter.com/wp-content/uploads/2020/04/window-chrome.png

**Comment by mchampaneri** [comment]
@c-smile 

Yes, It works for window-frame extended.

Thanks,
Manish
