### ISSUE TITLE
[Bug] tuple-template is broken in version 4.4.2.5

### ISSUE THREAD

**Issue by MaherFa** [c-smile/sciter-sdk#157]
Minimal code to reproduce:
`$(body).append ([div: { class:"myclass" },[p: "mytext" ]]);`

the mentioned code will cause the app to crash silently, without displaying any errors.

**Comment by c-smile** [comment]
I'll fix it so it will not crash, but your construction is not a [vnode](https://sciter.com/docs/content/script/language/ssx.htm) anyway .

It is better to use SSX instead of that cryptic microformat :
```
$(body).append( <div.myclass><p>mytext</p></div> ); 
```
Or if mytext is a variable:
```
var mytext = "Hello world!";
$(body).append( <div.myclass><p>{mytext}</p></div> ); 
```
SSX makes intentions clearer I think.

**Comment by MaherFa** [comment]
> SSX makes intentions clearer I think.
I Agree.
