### ISSUE TITLE
[Documentation] view.audio(url)

### ISSUE THREAD

**Issue by MaherFa** [c-smile/sciter-sdk#158]
the audio playback object added in version 4.4.1.5 is a welcomed addition.

but the docs have nothing about this object and its properties and methods.

I understand that it is a work in progress as mentioned in the log file but a very basic list would be great.

**Comment by c-smile** [comment]
Umm... and what about this: https://htmlpreview.github.io/?https://github.com/c-smile/sciter-sdk/blob/master/doc/content/sciter/Audio.htm ?

**Comment by MaherFa** [comment]
this does it, sorry I missed the offline docs..
I was searching in [https://sciter.com/docs/content/sciter/View.htm](https://sciter.com/docs/content/sciter/View.htm)

**Comment by c-smile** [comment]
Thanks, it is there now: 
https://sciter.com/docs/content/sciter/Audio.htm
