### ISSUE TITLE
[Bug][Windows] Inspector possible memory leak

### ISSUE THREAD

**Issue by MaherFa** [c-smile/sciter-sdk#159]
latest version 4.4.2.5
Windows 10 x64

Inspector increasingly uses up too much RAM before becoming too laggy and closing it self.
Issue is present even with plain scapp.exe (x32/x64) without loading any app.

![Inspector in Task Manager](https://user-images.githubusercontent.com/20836213/79076196-e7c2d980-7d00-11ea-8f08-16bd002bac6c.jpg)

**Comment by c-smile** [comment]
Try 4.4.2.6 please. Will you have the same problem?

**Comment by MaherFa** [comment]
The Issue seems to be gone with 4.4.2.6, Inspector is working as expected. Thank You.
