### ISSUE TITLE
[Question] Does this use Pawn?

### ISSUE THREAD

**Issue by StunxFS** [c-smile/sciter-sdk#167]
Does this use Pawn? Github has been saying for days that Sciter contains Pawn code.
Here's a test image:
![imagen](https://user-images.githubusercontent.com/56417208/82234935-120b4680-9900-11ea-9dab-ba8dd39ea98a.png)

**Comment by c-smile** [comment]
No. 

I don't even know what the Pawn is it and why GitHub put it there.

**Comment by StunxFS** [comment]
Okay. Pawn is an extension language that contains a C-like syntax, maybe that's why GitHub put it there.

By the way, thanks for developing Sciter!
