### ISSUE TITLE
Inspector channel socket error:no such file or directory

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [c-smile/sciter-sdk#175]
Inspector channel socket error:no such file or directory,why?

**Comment by LeiZhang-Hunter** [comment]
what's to be done

**Comment by LeiZhang-Hunter** [comment]
can i help you?

**Comment by LeiZhang-Hunter** [comment]
can i help you?

**Comment by c-smile** [comment]
OS and Sciter version ?

In what application is that? In yours or in usciter app from SDK?
