### ISSUE TITLE
How are "notes" and "notepad" licensed under?

### ISSUE THREAD

**Issue by guojize** [c-smile/sciter-sdk#176]
I'm making an open source project and it need an WYSIWYG rich text editor. I want to use some of the code of `notes` and `notepad` distributed by `sciter-sdk` release. I wonder am I allowed to do so?

**Comment by c-smile** [comment]
> I wonder am I allowed to do so?

Yes, all samples are BSD licensed.

**Comment by guojize** [comment]
Thanks! @c-smile
