### ISSUE TITLE
Implement toFixed() for Float

### ISSUE THREAD

**Issue by SonnyX** [c-smile/sciter-sdk#179]
I just found out that sciter does not have a `toFixed` function, and only has ` String.printf("%.1f", download_progress)` as a substitute.
It might be nice to include a `toFixed` function in the future.

**Comment by c-smile** [comment]
> It might be nice to include a toFixed function in the future.

Sure, just define it if you need that:

```
function Float.toFixed(frac) {
  return String.printf("%.*f", frac,this);
}

debug log: (3.1415).toFixed(2); // outputs "3.14"

```
