### ISSUE TITLE
Non-URI compliant behavior

### ISSUE THREAD

**Issue by SonnyX** [c-smile/sciter-sdk#180]
https://stackoverflow.com/questions/3616795/what-is-the-difference-between-file-file-file
![afbeelding](https://user-images.githubusercontent.com/784475/88859320-c9261700-d1f9-11ea-80a2-ecbe3d5ef5e6.png)

**Comment by c-smile** [comment]
What's that?

**Comment by SonnyX** [comment]
```
file:// is the prefix for the file protocol

file:/// is the prefix for the file protocol, plus a leading / pointing to the root directory of the current drive (On Windows) or the overall root directory (On Linux / Unix). 
```
For some reason sciter does not like `file:///C:/...` on windows, even though that is how it is (and should be) used elsewhere. e.g. browsers.

**Comment by c-smile** [comment]
That's debatable.

First,  `C:/` on Windows is marker of FS root.  And second, having this url `file://foo.bar` what would be the used path ?

**Comment by SonnyX** [comment]
That would depend on the `Working Directory`/``pwd` in my assumption, thus it being a relative path instead.
However I'm merely stating how I have seen other libraries and applications implement the paths for the file protocol.
I'll close this since I feel like this is a "Won't fix"
