### ISSUE TITLE
Shift+Mousewheel does not perform horizontal scroll

### ISSUE THREAD

**Issue by martinlombana** [c-smile/sciter-sdk#187]
I supose it's not a "bug", maybe. But that is the common behaviour and it doesn't seem to work out of the box. 

Take this window, for instance. 

![image](https://user-images.githubusercontent.com/18351919/98590185-bc23c400-22ce-11eb-8ac6-d3236b449bf4.png)

**Comment by c-smile** [comment]
Fixed in Sciter 4.4.5.11
