### ISSUE TITLE
Inspector  error

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [c-smile/sciter-sdk#190]
windows:

demo bin.win

Inspector channel socket error:no such file or directory.

why?

**Comment by LeiZhang-Hunter** [comment]
Sciter version 4.4.4.6

**Comment by MasterCna** [comment]
Same here, also the `expand()` function will crash automatically on some systems

**Comment by c-smile** [comment]
@MasterCna  I do not see any problems here nor I have reports about it.

**Comment by c-smile** [comment]
@LeiZhang-Hunter 

> Inspector channel socket error:no such file or directory.

That may happen if inspector is failed or it takes too much time for that.

Try to start inspector.exe first and then your application.
