### ISSUE TITLE
Provide overloads with wchar_T in non Windows systems

### ISSUE THREAD

**Issue by NN---** [c-smile/sciter-sdk#205]
For instance this code doesn't compile on Mac:

```cpp
// string get(const WCHAR* defv) const
get(L""); // Cannot convert wchar_t const* to WCHAR
```

**Comment by c-smile** [comment]
You can use either:
```
get(u"")
```
Or there is WSTR(string literal) for that:
```
get(WSTR(""))
```
See: https://en.cppreference.com/w/cpp/language/string_literal

**Comment by NN---** [comment]
`u""` has type  `const char16_t[N]` while there is no such overload.
char16_t is a distinct type.
