### ISSUE TITLE
Question about BrokenHeart error

### ISSUE THREAD

**Issue by kk-andrey** [c-smile/sciter-sdk#206]
I'm using Reactor  and I started to face a BrokenHeart error and it looks like this: 
`Wrong type - BrokenHeart([object BrokenHeart]), expected instance of object, attempt to set property "class" on GCed object`

or this:
`BrokenHeart([object BrokenHeart])) has no property - class.`

This error is super rare and has no straightforward pattern to reproduce, so i would like to ask, get some advice maybe: what this error is and what can cause it?

Platform: Windows 10 Enterprise (19041)
SciterSDK: 4.4.5.9

**Comment by 105th** [comment]
@kk-andrey this error was fixed in 4.4.6.2
you should update to 4.4.6.6
