### ISSUE TITLE
build error on linux platform (miss sciter-sqlite.make file)

### ISSUE THREAD

**Issue by kay54068** [c-smile/sciter-sdk#209]
I run 'make config=release_x64' command to build demo app, but get some error about this:

==== Building sciter-sqlite (release_x64) ====
make[1]: sciter-sqlite.make: No such file or directory
make[1]: *** No rule to make target 'sciter-sqlite.make'.  Stop.
Makefile:139: recipe for target 'sciter-sqlite' failed
make: *** [sciter-sqlite] Error 2

Can you give me a hand?

**Comment by c-smile** [comment]
I've added that make file.

Note, you can always [re]generate those files using premake5 by running in SDK folder:
```
premake5 gmake2 --cc=gcc --file=premake5.lua
```
