### ISSUE TITLE
sciter.dll from bin.win folder does not work

### ISSUE THREAD

**Issue by ekuiperemr** [c-smile/sciter-sdk#211]
I have an old version of sciter.dll that works fine with the application rustdesk.

But when I use the fresh small DLL from bin.win directory, it does not run.
I get this error
thread 'main' panicked at 'error: 'sciter.dll' was not found neither in PATH nor near the current executable.
  Please verify that Sciter SDK is installed and its binaries (from SDK/bin/64) are available in PATH.'

But when I replace this sciter.dll with the old one it just works fine.

Please help. I would like to use the small DLL please.

**Comment by wdcossey** [comment]
Think you would need to provide some more information:

1. What version is your `old version`?
2. Is this for an `x86` or `x64` project (I assume `x64` from the error message)?
3. What version is the `fresh small DLL`?
4. Can you explain what `small` dll you are talking about, is this `Sciter Lite`, is you app compatible with the `lite` version?
5. Have you updated your rust bindings [(link)](https://github.com/sciter-sdk/rust-sciter/blob/1b610fcb7414b3257f6723821e2d9c0cc5aed6ed/src/lib.rs#L209)?
6. If this is a rust issue it may be quicker to get help from @pravic as he maintains [rust-sciter](https://github.com/sciter-sdk/rust-sciter)

**Comment by c-smile** [comment]
There are two sciter x64 Windows binaries:  

[sciter-sdk/bin.win/x64/sciter.dll](https://github.com/c-smile/sciter-sdk/blob/master/bin.win/x64/sciter.dll) - 7.86 MB - this includes Direct2D + GDI+ backend.
[sciter-sdk/bin.win/x64skia/sciter.dll](https://github.com/c-smile/sciter-sdk/blob/master/bin.win/x64skia/sciter.dll) - 9.66 MB - this includes Direct2D + Skia/OpenGL backend (so it is larger).

I have no idea where these 149K comes from.

**Comment by ekuiperemr** [comment]
Okay - Thank you.
