### ISSUE TITLE
Question: #define _WINSOCKAPI_ within Sciter (and Boost.Asio)

### ISSUE THREAD

**Issue by volkan-ozdemir** [c-smile/sciter-sdk#213]
Hi,

I'm currently trying to build Sciter with Boost.Asio (https://www.boost.org/).

I saw the following lines on couple of Sciter header files:

```
#if defined(_WIN32)
  #ifndef WIN32_LEAN_AND_MEAN
    #define WIN32_LEAN_AND_MEAN
  #endif
  #define _WINSOCKAPI_
  #include <windows.h>
#endif
```

It looks like Sciter doesn't use winsocks. So in this case, what is the purpose behind `_WINSOCKAPI_ `definition?

So long as WIN32_LEAN_AND_MEAN is defined, then "winsock.h" won't be included anyway.

Problem is Asio also contains the following line of code and doesn't compile.

```
# if defined(_WINSOCKAPI_) && !defined(_WINSOCK2API_)
#  error WinSock.h has already been included
# endif // defined(_WINSOCKAPI_) && !defined(_WINSOCK2API_)
```
I solved the issue by including Boost.Asio before Sciter but I'm still concerned about internals of Sciter.

Could someone confirm that Sciter doesn't use winsock.h and  `#define _WINSOCKAPI_` is not necessary?

**Comment by c-smile** [comment]
Yeah, those are remnants of previous versions.

I've removed them [here](https://github.com/c-smile/sciter-js-sdk/commit/c39d79e00df0375ed0c7f57639c3271a9def6b15)
