### ISSUE TITLE
1000+ Data performance

### ISSUE THREAD

**Issue by xxscloud5722** [c-smile/sciter-sdk#216]
<script type="text/javascript">
        setTimeout(() => {
            let ul = '';
            for (let i = 0; i < 10000; i++) {
                ul = ul + '<li>DD: ' + i + '</li>'
            }
            document.querySelector('#vlist').append(ul)
        })
    </script>

<vlist id="vlist">
    <li>xxxx</li>
</vlist>

mac 12.0.1, sciter 4.6.x, 10000 data is very stuck, dragging to a point and scrolling will get stuck for one second

**Comment by xxscloud5722** [comment]
<vlist id="vlist">
    <li>xxxx</li>
</vlist>

**Comment by xxscloud5722** [comment]
```
<vlist id="vlist">
    <li>xxxx</li>
</vlist>
```

**Comment by xxscloud5722** [comment]
Drag the scroll bar to any position, then the scrolling data will be stuck for a second

**Comment by c-smile** [comment]
Please try the same in Sciter JS SDK https://github.com/c-smile/sciter-js-sdk/tree/main/samples.sciter/virtual-list
Will you see the same problem?

**Comment by xxscloud5722** [comment]
Sorry, can you have a JS demo?
I think using `vlist` can achieve big data loading

**Comment by xxscloud5722** [comment]
Sorry, can you have a demo of js

**Comment by c-smile** [comment]
Sciter.JS uses native implementation of virtual list.
Sciter.TIS uses script based virtual list implementation: https://github.com/c-smile/sciter-sdk/blob/master/samples/%2Bvlist/vlist.tis so you can investigate your problem there.

That if I understand you properly.

**Comment by c-smile** [comment]
```JS
<script type="text/javascript">
    setTimeout(() => {
        let ul = '';
        for (let i = 0; i < 10000; i++) {
            ul = ul + '<li>DD: ' + i + '</li>'
        }
        document.querySelector('#vlist').append(ul)
    })
</script>
```
you create 10000 DOM elements. 

It should not be a surprise that you have runtime delays.

You shall use virtual list to show potentially large sets.
