### ISSUE TITLE
Mac OS 应用程序“inspector”无法打开。

### ISSUE THREAD

**Issue by xxscloud5722** [c-smile/sciter-sdk#218]
应用程序“inspector”无法打开。

**Comment by xxscloud5722** [comment]
MacBook Pro (15-inch, 2018)
12.2.1

**Comment by xs23933** [comment]
chmod +x {some path}/inspector.app/Contents/MacOS/inspector

cmd
/{some path}/inspector.app/Contents/MacOS/inspector

**Comment by xs23933** [comment]
or you try download. js new version Inspector 
https://github.com/c-smile/sciter-js-sdk
