### ISSUE TITLE
Windows 10 and UWP apps

### ISSUE THREAD

**Issue by suprak** [c-smile/sciter-sdk#26]
Does Sciter support UWP apps as part of the Windows 10 infra or is it WPF only?

**Comment by AndrewTerra** [comment]
UWP? Not yet but planning. 
As of WPF, Sciter has nothing with it. It is purely native engine that on Windows uses Direct2D as it is. On Mac OS X and Linux/GTK it uses CoreGraphics and Cairo graphics primitives.
