### ISSUE TITLE
A problem of frame|pager

### ISSUE THREAD

**Issue by gxlmyacc** [c-smile/sciter-sdk#3]
Hi, Andrew, see this gif:
<a href="http://i12.tietuku.com/aad88d1a86d08e0e.gif" title="点击显示原始图片"><img src="http://i12.tietuku.com/aad88d1a86d08e0et.jpg"></a>

**Comment by c-smile** [comment]
It used to be such a problem, but I do not see it in 3.3.0.7. 
What version do you use?

**Comment by gxlmyacc** [comment]
It's 3.3.0.7, and I fount that it's related to the Chinese path

**Comment by c-smile** [comment]
How exactly it is related to the Chinese path? Any details?

**Comment by gxlmyacc** [comment]
When I move "(SDK)\samples\printing" to "D:\printing", It's work is OK, but When I move it to "D:\新建文件夹\printing", It's work will has some problem.

**Comment by gxlmyacc** [comment]
I found that it will be OK when I changed the "contentUrl = self.url( this.value );" to "contentUrl = this.value;" in pager-demo.htm
