### ISSUE TITLE
SciterSetupDebugOutput(hwnd, ..) don't work for child windows

### ISSUE THREAD

**Issue by midiway** [c-smile/sciter-sdk#35]
In [OmniView](https://github.com/midiway/OmniView) I create multiple Sciter child HWNDs, one for each document user opens in VS, and for each HWND I set a `SciterSetupDebugOutput(hwnd, ..)`

Problem is: the DEBUG_OUTPUT_PROC callback is never called with output messages...

If I call `SciterSetupDebugOutput(NULL, ..)` it does work, but I can't use it this way because I need to receive the messages specific for the given Sciter HWND.

**Comment by midiway** [comment]
BUMP

**Comment by c-smile** [comment]
If your window is using SW_ENABLE_DEBUG flag sciter set up alternative debug output destination.
Therefore SciterSetupDebugOutput is applicable only when you do not use SW_ENABLE_DEBUG or 
SciterSetOption(SCITER_SET_DEBUG_MODE) .
