### ISSUE TITLE
Element.animate() is stoped if window is minimized

### ISSUE THREAD

**Issue by midiway** [c-smile/sciter-sdk#39]
```JS
var i = 0;
self.animate(function() {
	log("anim", i++);
	return 100;
}, function() {
	log("end");
});
```
If I minimize the window, the animation is ended. Bug or is it by design?

**Comment by c-smile** [comment]
That's by design. Use `view.on("statechange", ...) ` if you have restartable animations.

**Comment by midiway** [comment]
But what if I simply don't want this behavior to happen? Why do I need to circumvent it?
That is, engine is simply killing an ongoing animation...

**Comment by c-smile** [comment]
'cause engine has no idea what you are animating.

Say you have collapsing section animation that takes 1 second. While animating you minimize and restore the window in two seconds. Do you expect that animation to run after restoration?

**Comment by midiway** [comment]
no

**Comment by c-smile** [comment]
And what should happen if while animating you minimize and restore the window in half a second ?
Shall you see that animation running?

**Comment by midiway** [comment]
yes

**Comment by c-smile** [comment]
Do you expect step() callback to be called when window is hidden ? If "yes" then what about batteries ?
MacOS for example reduces frequency of timers 10 or so times when window is iconified.

For image infinite animations (gif,png) sciter freezes animations and re-starts them at the state they were frozen. To be short it could be various policies of doing this. Shall I implement them all ? That definitely needs to be configurable somehow.
