### ISSUE TITLE
Element.animate() end callback should allow starting another animate()

### ISSUE THREAD

**Issue by midiway** [c-smile/sciter-sdk#40]
```
var i = 0;
self.animate(function() {
    if(i++ == 10)
        return 0;

    return 100;
}, function() {
    stdout.println("First animate() ended, starting another one");

    self.animate(function(p) {
        stdout.println("This is called only once", p);// BUG: should allow starting another animation
    }, 10000);
});
```

**Comment by c-smile** [comment]
I am not sure I understand why do you expect that `self.animate(function(p) ` to run more than once in that case.

Did you mean to put that code in 
`self.on("animationend", function() {...});
`
? That handler will run on when any animation has ended.

**Comment by midiway** [comment]
suppose an infinite loop animation, where you do it back and forward, so at its end, you start it again, repeatedly...

That is, the 'onEnd' callback of animate() should support starting a new animation again.
I don't understand why it doesn't since the previous animation has just ended (theoretically disposed)...

**Comment by c-smile** [comment]
Finally I've got what you mean.

Try this

```
      var i = 0;
      self.animate(function() {
          if(i++ == 10)
              return 0;

          return 100;
      }, function() {
          stdout.println("First animate() ended, starting another one");
             
          this.post( function() {  
            self.animate(function(p) {
                stdout.println("This is called only once", p);
            }, 10000);
          });
      });    

```

**Comment by midiway** [comment]
That way works, but I don't understand why I need to `post()` a new callback. Seems like engine needs to be fixed to call the 'onEnd' callback only after it is ready to start a new animate() in that same element...

**Comment by c-smile** [comment]
fixed by internal revision 4227
