### ISSUE TITLE
Curl Version Issues

### ISSUE THREAD

**Issue by dhtseany** [c-smile/sciter-sdk#50]
Hello,
While not directly related to your work, I'm attempting to run an app that uses libsciter-gtk-64.so to provide readouts of system information on a user's desktop. However, I'm hitting the following error regarding CURL versions, even though I'm pretty sure I have any and all CURL options available to Arch linux installed on my system.

`Unable to load library: /usr/lib/libcurl.so.4: version 'CURL_OPENSSL_3' not found (required by /usr/bin/libsciter-gtk-64.so)`

The file exists on my system per the filepath above (/usr/lib/libcurl.so.4) so I'm hung up trying to figure out why it's disregarding it. Any chance you can clue me in as to what version of CURL libsciter-gtk-64.so is exepecting to use? Thanks!

**Comment by c-smile** [comment]
Starting Sciter v.4.0.0.2 Sciter loads libcurl on demand using dload. So it is using installed CURL version
