### ISSUE TITLE
sciter.exe load htm failed in windows-10

### ISSUE THREAD

**Issue by Picktarget** [c-smile/sciter-sdk#51]
Enviornment:win10 64
question:when I clicked the button load htm,the sciter.exe Get stuck and crashed at last.

**Comment by c-smile** [comment]
I need more details on this. Is it about loading of any html or just particular one?

**Comment by Picktarget** [comment]
Is it about loading of any html .mybe,it's my os fault.when I use it in my own PC. it gets working well
