### ISSUE TITLE
Support for font loading on Linux.

### ISSUE THREAD

**Issue by mike168m** [c-smile/sciter-sdk#53]
Is it possible to have font loading support on Linux.

**Comment by c-smile** [comment]
It seems that there is still no straightforward way of loading fonts from memory in pango/cairo (used by default in Sciter). Skia backend supports that though.

You can select Skia backend by calling :

SciterSetOption(NULL,SCITER_SET_GFX_LAYER,GFX_LAYER_SKIA_CPU); // or
SciterSetOption(NULL,SCITER_SET_GFX_LAYER,GFX_LAYER_SKIA_OPENGL);

at startup. Problem is that Skia backend is not "native" for GTK so may work a bit slower.
