### ISSUE TITLE
bug-Mac OSX-notes can not insert iamge

### ISSUE THREAD

**Issue by aisnote** [c-smile/sciter-sdk#62]
![image](https://user-images.githubusercontent.com/1201634/31204271-e5ce84ba-a91f-11e7-9fb0-aae1c43de1dc.png)

**Comment by c-smile** [comment]
Yeah, that button has no event handler yet on any platform. 
Pasting images from clipboard or from browser - works.

**Comment by aisnote** [comment]
I tried on MacOs, capture the image or copy image from browser, then paste. Command + V or use right popup menu paste, it can not work.

**Comment by c-smile** [comment]
Fixed
