### ISSUE TITLE
TWO windows appear

### ISSUE THREAD

**Issue by hasanOryx** [c-smile/sciter-sdk#64]
I tried loading a simple html file using `Rust`, it is loading fine at `cargo run`, but once I run the `.exe` alone, 2 windows appear, one empty as `cmd` and one shows the real output as shown in this pic.

I'm using `Windows 10 x64`

![image](https://user-images.githubusercontent.com/26045838/33519214-93f8d560-d7b3-11e7-9461-9219f6db571f.png)

**Comment by c-smile** [comment]
It appears as you have compiled your executable as console app so Windows creates console window for it (that second black window).

Your compilation command line should look like: 
`cargo rustc -- -Clink-args="/SUBSYSTEM:WINDOWS"`

Check this:
https://github.com/rust-lang/rfcs/blob/master/text/1665-windows-subsystem.md

**Comment by hasanOryx** [comment]
I compiled it as 'cargo build --release' will check using the one you provided and confirm you back, thanks

**Comment by pravic** [comment]
Also `#![windows_subsystem="windows"]`, see sciter-sdk/rust-sciter#21.

**Comment by hasanOryx** [comment]
Thanks @pravic  that solved it.
