### ISSUE TITLE
Question: Where is documented CSS behaviour built in values?

### ISSUE THREAD

**Issue by Aukstkalnis** [c-smile/sciter-sdk#65]
I tied to search the wed, but not found this list. I was curious where defined behaviour: switch in details. Is there are such documentation?

**Comment by pravic** [comment]
Native behaviors are documented [here](https://sciter.com/developers/sciter-docs/native-behaviors/).

As for the `switch` - are you talking about [this switch](https://github.com/c-smile/sciter-sdk/tree/master/widgets/switch) from widgets?

**Comment by Aukstkalnis** [comment]
Well no. This switch is prototyped with code and css. I am asking about built in behavior: switch. I saw it used in examples with tabs.

**Comment by pravic** [comment]
Can you give a link or a name of such example?

**Comment by Aukstkalnis** [comment]
Sure. sciter-sdk\samples\drag-n-drop-manager\tabs.htm:18.

**Comment by c-smile** [comment]
Unfortunately it is not documented yet.

behavior:switch is a behavior:radio so only one element in a group is at `:checked` state any time.

The only difference is that behavior:radio switches state of the group on MOUSE_UP and behavior:switch does the switch on MOUSE_DOWN.
