### ISSUE TITLE
[Sample] SFML ?

### ISSUE THREAD

**Issue by RUSshy** [c-smile/sciter-sdk#67]
Hi,

I see there is sample with GLFW, is it possible to create similar sample for SFML ?

Thanks, amazing library!

**Comment by c-smile** [comment]
Let's do it together. Create basic SFML application with window - I'll add Sciter support to it.

**Comment by RUSshy** [comment]
Oh thanks!

I created cmake project ready here https://github.com/RUSshy/sfml-sciter

**Comment by RUSshy** [comment]
or should i create project like ``demo.GLFW`` and send PR ?

**Comment by Milerius** [comment]
Any news ?
