### ISSUE TITLE
A problem about apng

### ISSUE THREAD

**Issue by gxlmyacc** [c-smile/sciter-sdk#7]
Hi, Andrew， Here is my code:
<pre>
&lt;html&gt;
 &lt;head&gt;
  &lt;style type=&quot;text\css&quot;&gt;
    div.float {
      background-image: url(bg.png);
      background-position: center center;
      background-repeat: no-repeat;
      size: 100dip;
    }
    
  &lt;/style&gt;    
  &lt;script type=&quot;text/tiscript&quot;&gt;
     function self.ready() {
       $(#test).move(100, 100, #view, #attached-window);
     }
  &lt;/script&gt; 
 &lt;/head&gt;
 &lt;body style=&quot;&quot;&gt;
    &lt;div.float #test /&gt;
 &lt;/body&gt;
&lt;/html&gt;
</pre>
and here is result：
<a href="http://i5.tietuku.com/b59d27a88aa27ec9.gif" title="点击显示原始图片"><img src="http://i5.tietuku.com/b59d27a88aa27ec9t.jpg"></a>
<hr />
so I think the popup window maybe has some wrong with apng

**Comment by c-smile** [comment]
Current version (3.3.0.7) has problems with some aPNGs and aGIFs. They are fixed already here. Please wait for 3.3.0.8.
