### ISSUE TITLE
A potential problem with Graphics reference count

### ISSUE THREAD

**Issue by pravic** [c-smile/sciter-sdk#75]
This:

https://github.com/c-smile/sciter-sdk/blob/1f6f9afc6bf3c4f60ea510fc75f89634f282d15d/include/sciter-x-graphics.hpp#L263-L266

It looks like we manually add a reference to the unwrapped value (like we do that for `image` and `path` as well), but the `sciter::graphics` increments it in its constructor too (which is needed by `image_paint_function()`):

https://github.com/c-smile/sciter-sdk/blob/1f6f9afc6bf3c4f60ea510fc75f89634f282d15d/include/sciter-x-graphics.hpp#L255-L258

Sorry if I miscounted it.

**Comment by c-smile** [comment]
Yes, `gapi()->gAddRef(hgfx);`  is definitely not needed there, even worse - may lead to mem-leak.
Same is with `path path::from()` method. I've changed it here will update github ASAP

**Comment by pravic** [comment]
A potential fix in #76. If it looks okay.

**Comment by pravic** [comment]
Fixed in 4.1.7. 

I am not sure why `path` was changed too, but okay. Thanks!
