### ISSUE TITLE
How to Linking Sciter statically

### ISSUE THREAD

**Issue by MasterCna** [c-smile/sciter-sdk#78]
Hi, I did some tests for link statically but doesn't work at all. Can you give me some quick way how to link Sciter statically please?

**Comment by c-smile** [comment]
Public Sciter SDK does not contain sciter static libs so the question is irrelevant here. I've replied to you by e-mail directly.

**Comment by blacklat** [comment]
"... the question is irrelevant here ..."
why is it irrelevant? I think your posture is irrelevant here, the collaborator just asked a question. be nice to people, don't be an asshole.

**Comment by c-smile** [comment]
@blacklat 

"Irrelevant" is just a bad choice of word there I shall admit, indeed.  
Intention was to say "not applicable" [to binary engine distribution].

And definitely was not an intention to insult anybody. English is not my primary language after all.
