### ISSUE TITLE
<frame> src attribute only recognizes URL ended with .html or .htm

### ISSUE THREAD

**Issue by bsapwindows** [c-smile/sciter-sdk#79]
This won't load:
``` html
<frame src="https://httpbin.org/"></frame>
```

This will (return Not Found as intended):
``` html
<frame src="https://httpbin.org/index.html"></frame>
```

Not a very urgent issue though. Just thought it would be cool if I could open website with transparent background enabled. It gains the possibility to turn existing web pages into desktop gadgets as simple as adding an HTML tag. Well, a dying niche use case anyway...

**Comment by c-smile** [comment]
I do not see any problems with this: `<frame src="https://httpbin.org/"></frame>`, sciter.exe loads and renders instruction page at [httpbin.org](https://httpbin.org/) as browsers do.

Testing it with this document:

```
<html>
    <head>
        <title>Test</title>
    </head>
    <body>
      <frame src="https://httpbin.org/"></frame>
    </body>
</html>
```

**Comment by bsapwindows** [comment]
Weird. I'm using your code but it's still not working.

This is what I get in Sciter.exe:
![sciter.png](https://i.loli.net/2018/05/07/5af067924d79b.png)

And this is what showed in Inspector:
![inspector.png](https://i.loli.net/2018/05/07/5af067ac65ae0.png)

**Comment by bsapwindows** [comment]
OK it's working now, and also it loads google.com successfully. I didn't change any code, just reloaded the file many times. It should be problem on my end, possibly bad network. Chrome loads quite fast so I didn't think of that...

Any way, excuse me and thank you for your time... :sweat:

**Comment by c-smile** [comment]
Seems like httpbin.org is quite busy site - long delays.
