### ISSUE TITLE
How to use plus framework to implement conditional render?

### ISSUE THREAD

**Issue by AllenDang** [c-smile/sciter-sdk#82]
My ip address is blocked by the official forum, don't know why... so I ask the question here.

What I want to do is conditional render like:

namespace Data {
  var p = {Type:"text", Title:"Something"};
}

if p.Type == "text" {
  <plaintext .../>
} else {
  <image .../>
}

What's the best approach to implement this?

**Comment by c-smile** [comment]
forum blocks IP a) only temporarily and b) when it detects too many attempts to login with wrong credentials. Reason is obvious I think.

As of rendering:
```
var container = ...

if (p.Type == "text") {
   container.$content(<textarea value="{p.Value}"/>);
} else {
   container.$content(<picture src="{p.Value}" />);
}
```
where `container.$content(...html...)` is a bultin variant of React's RXJS, equivalent of container.html = "...html...";` but with parameter's  interpolation.

**Comment by AllenDang** [comment]
Thanks very much! I solved it by using behavior to override value property with the $content binding.
