### ISSUE TITLE
Enumerating a tiscript object in c++ seems to be broken

### ISSUE THREAD

**Issue by Nathan1852** [c-smile/sciter-sdk#84]
I updated sciter-gtk.so from version 4.1.5.5856 today because of the window closure sequence bug and now enumerating an tiscript object only returns an empty key and a symbol instead of the keys and values of the object.

It works again when I replace it new .so with the old one.

**Comment by c-smile** [comment]
How do you "enumerating an tiscript object" ?

**Comment by Nathan1852** [comment]
I am using the tiscript::enumerator for this.

Example: 

nlohmann::json tisObjToJson( HVM vm, nlohmann::json j, tiscript::value obj ) {
&nbsp;&nbsp;&nbsp;&nbsp;tiscript::enumerator each( vm, obj );
&nbsp;&nbsp;&nbsp;&nbsp;for( tiscript::value key, val; each( key, val );) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if( tiscript::is_string( val ) ) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;j[ k ] = strdup( aux::w2utf( tiscript::c_string( val ) ).c_str() );
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else if( tiscript::is_int( val ) ) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;j[ k ] = tiscript::c_int( val );
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else if( tiscript::is_float( val ) ) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;j[ k ] = tiscript::c_float( val );
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else if( tiscript::is_bool( val ) ) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;j[ k ] = tiscript::c_bool( val );
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else if( tiscript::is_symbol( val ) ) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;j[ k ] = strdup( aux::w2utf( tiscript::c_symbol( val ) ).c_str() );
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else if( tiscript::is_array( val ) ) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;j[ k ] = tisArrToJson( vm, nlohmann::json::array(), val );
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else if( tiscript::is_object( val ) ) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;j[ k ] = tisObjToJson( vm, nlohmann::json::object(), val );
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} else {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;j[ k ] = nullptr;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;return j;
&nbsp;&nbsp;}

**Comment by Nathan1852** [comment]
Oops, I removed it accidentally while copying it to github.
I added it to my previous comment.
k is declared like this: std::string k = aux::w2utf( tiscript::c_string( key ) ).c_str();

**Comment by c-smile** [comment]
And what are "empty key and a symbol instead" exactly?

**Comment by Nathan1852** [comment]
The only pair that gets added to the nlohmann::json object with the function above is an empty string as  key "" and the value "nothing" as string.
At least in the new sdk version

**Comment by Nathan1852** [comment]
Thank you.
Are there any news about this problem?

**Comment by Nathan1852** [comment]
Thank you for the fix. But sadly there seems to be one problem remaining. 
It now seems like the key and value are switched, meaning that this
`tiscript::enumerator each( vm, obj );
for( tiscript::value key, value; each( key, value);) {}`

now has the objects key in the "value" variable and the objects value in the "key" variable

**Comment by c-smile** [comment]
Thanks, fixing.

**Comment by Nathan1852** [comment]
Thank you for fixing this

I'm sorry to say that I have found another Issue.
Sciter crashes with a Segmentation fault when I set a mediaVar in a frame while I have at least one svg shown on screen. While I can reproduce it with libsciter-gtk.so on ubuntu every time, I can't reproduce it on Windows or with usciter. 
I can send you a complete gdb backtrace of the functions called up to the crash,if you want to take a look at this.
I didn't want to open another github issue because sadly it is really vague right now.

**Comment by c-smile** [comment]
Stack trace will be enough, thanks in advance.

**Comment by Nathan1852** [comment]
The stack trace in question: https://pastebin.com/xZtBNrLj
Thank you for looking into this

**Comment by c-smile** [comment]
Thanks, is it possible to get somehow minimal html/css/svg set where this is reproducible. So far I cannot reproduce it on smaples that I have here.

**Comment by Nathan1852** [comment]
[segfault_example.zip](https://github.com/c-smile/sciter-sdk/files/2129320/segfault_example.zip)
I've attached an example. Just start usciter, open the main.htm and click on the tab named "Crash tab".
It should segfault immediately,I could reproduce it every time.

**Comment by Nathan1852** [comment]
Thank you very much for the quick fix
