### ISSUE TITLE
Endless events

### ISSUE THREAD

**Issue by Mikanoshi** [c-smile/sciter-sdk#91]
Appeared in version 6172.
When using SciterAttachEventHandler() (on root element for example) and then hovering mouse over the Sciter window event procedure starts getting SUBSCRIPTIONS_REQUEST, HANDLE_INITIALIZATION, HANDLE_MOUSE indefinitely. Same happens with any event, if you focus window without using mouse then loop will have HANDLE_FOCUS event.

https://github.com/Mikanoshi/SciDe/blob/master/source/Sciter.pas#L1182

**Comment by c-smile** [comment]
I cannot reproduce this on samples of native behaviors from the SDK.

For each particular element/behavior HANDLE_INITIALIZATION shall happen on element construction/destruction.  

It appears as your code reloads document in a loop or something like that.

**Comment by Mikanoshi** [comment]
Why 6143 and every single version before was working then? I only changed DLL. Some latest changes caused that, don't even know where to look... Without SciterAttachEventHandler() program does not have any sign of activity, so I doubt it's doing anything. Also that endless loop was without any delays, so program's UI thread just uses all resources of 1 CPU core and freezes completely.

**Comment by pravic** [comment]
@Mikanoshi Just out of curiosity: can you [try 6143](https://github.com/c-smile/sciter-sdk/tree/03bc2bf3eaa42a5b9d8e63e4b0fc9e24d1b3b9b5/bin) again?

**Comment by Mikanoshi** [comment]
Yes, 6143 works. This seems to be the problem:
https://github.com/Mikanoshi/SciDe/blob/master/source/Sciter.pas#L3992

If event param has a target that is not null new element object is being created and new listener is attached, hense the loop.

**Comment by c-smile** [comment]
I have some doubts about this:

```
function ElementFactory(const ASciter: TSciter; const he: HELEMENT): TElement;
begin
  Result := TElement.Create(ASciter, he);
end;
```
What if `he` (DOM element) already has  `TElement` instance created for it?
Why it creates new instance each time when it gets called for the same element?

I think it shall check first if that element is already in this map:
```
  FSciter.ManagedElements.Add(Self);
```
No?

Otherwise this will create new TElement on each MOUSE_MOVE event for example. No?

**Comment by pravic** [comment]
For me, the question is why would you want to attach a new event handler to the `params.heTarget` instead of just wrapping it in `TElement`? Or, even, doing that lazily during  [`TElementOnControlEventArgs.Target`](https://github.com/Mikanoshi/SciDe/blob/master/source/Sciter.pas#L134) reading?

What was the idea behind `SciterAttachEventHandler` in `TElement`?

**Comment by c-smile** [comment]
> What was the idea behind of the SciterAttachEventHandler in TElement?

I suspect that they want to catch element destruction notification from engine's side. But why they would need that is unknown. As soon as TElement holds reference of DOM element it is alive, it could be not connected to the DOM but is valid.

**Comment by Mikanoshi** [comment]
Because it causes Access Violation? No idea, I didn't write the wrapper :)
You get element and event handler attached to it supposed to make all the event listeners work, e.g.:
```delphi
var
  el: IElement;
begin
  el := Sciter.Select('#test');
  TElement(el).OnMouse = TreatMouseEvents;
end;
```

But var has to be used elsewhere, because it's an interface and manages references automatically, variable is destroyed if no longer used. I tried to add elements to ManagedElements and then check them, but it doesn't work for 2 reasons - above one is the first, FTarget is destroyed after HandleMouse() finishes, second one is that Sciter keeps sending mouse events for <html> element even after listener is detached.
I added logging to element creation/destruction and on old version creating and destroying TElement for root (<html>) does not cause additional events when moving mouse over Sciter window.

**Comment by c-smile** [comment]
> TElement(el).OnMouse = TreatMouseEvents;
It needs event handler creation only on OnMouse property assignment.

**Comment by Mikanoshi** [comment]
Does it matter? If there is no assignment the TElement is destroyed and event handler is detached. Only I think Sciter does no do that for root html, so elements for the target param are being created and destroyed, but listeners pile up.

**Comment by c-smile** [comment]
> that Sciter does not do that for root html

Does not do what exactly?

**Comment by c-smile** [comment]
> but listeners pile up.

Yes, that architecture of Delphi wrapper is tend to pile up memory. Yet to slow down event handling on each event received.

**Comment by Mikanoshi** [comment]
Listeners pile up in Sciter, not Delphi :) 

> Does not do what exactly?

Remove listener after SciterDetachEventHandler() call.
I only have 1 place where SciterAttachEventHandler() is called, and for each call there is a SciterDetachEventHandler() call with the same arguments, but 6172 keeps sending events to the event proc (_SciterElementEventProc).

**Comment by c-smile** [comment]
There is a problem with `SciterDetachEventHandler()` at the moment. Looking.

**Comment by c-smile** [comment]
I've updated Windows binaries here, on GitHub. Check them please.

**Comment by Mikanoshi** [comment]
Fixed 👍
