### ISSUE TITLE
Everything that's wrong with plaintext

### ISSUE THREAD

**Issue by Mikanoshi** [c-smile/sciter-sdk#93]
~1. In 6175:~
![1](https://user-images.githubusercontent.com/5113439/45259827-7964b980-b3ef-11e8-8bbf-72b6cb646c5a.jpg)
~2.~
```html
<html>
<head>
<script type="text/tiscript">
	function self.ready() {
		var p = $(plaintext);
		p.selection.select([bookmark: p.first.firstNode, 1, false]);
		p.execCommand("edit:insert-text", "\n2\n\n4\n");
	}
</script>
</head>
<body>
	<plaintext>15</plaintext>
</body>
</html>
```

Result is 
```
1
2
5
4
```
instead of 
```
1
2

4
5
```
If inserted string is `\n2\n3\n4\n` then last new line after 4 is missing.
This code works:
```js
p.execCommand("edit:insert-break");
p.execCommand("edit:insert-text", "2");
p.execCommand("edit:insert-break");
p.execCommand("edit:insert-break");
p.execCommand("edit:insert-text", "4");
p.execCommand("edit:insert-break");
```

~3.  Caret always disappears after opening context menu.
https://sciter.com/forums/topic/caret-coordinates/#post-57569
And how to set input focus to plaintext programmatically without selecting a specific text node, just make caret appear at the same position it was before input focus was removed?~

~4. What's going on with the caret? Why it can't stand still? :)
https://sciter.com/forums/topic/change-event-is-unreliable/#post-57593~

**Comment by c-smile** [comment]
What's wrong with #1 ?

**Comment by Mikanoshi** [comment]
Ctrl+Z

**Comment by Mikanoshi** [comment]
№2 fixed in 6184
Shortcut is still without +

**Comment by Mikanoshi** [comment]
Also when inserting text with new lines it just removes them all.

**Comment by Mikanoshi** [comment]
`&platform-cmd-mod;` returns different strings on 6143 (Ctrl+) and on 6172 and above (Ctrl). Windows 10 1803

**Comment by c-smile** [comment]
6172 is the correct one.  &platform-cmd-mod; yields to CTRL (Windows,Linux) or to ⌘ on MacOS. 
`+` is not be included.

**Comment by Mikanoshi** [comment]
6195:
- Inserting text that has new lines in it (not at the end) adds an unnecessary new line at the end of the text that is being inserted (same with the copy/paste)
- Pressing End key in empty plaintext and pasting anything into it results in caret being placed on second character instead of after the last one, and if text has new lines it breaks plaintext markup instead.
Related to №4, why user has to see that "past edge" stuff he doesn't care about? Same with selecting text using mouse - 2 caret places between entities. Confusing!

**Comment by Mikanoshi** [comment]
Both above problems remain in 4.2.5.0 (only End + pasting text without new lines was fixed).
Additionally, if you press End, then type some text and try to add new line via pressing Enter, it won't work. Adding new line from clipboard works, but also breaks plaintext layout.

**Comment by Mikanoshi** [comment]
4.2.6.1:
- Selection jumps back to starting point when using Shift+Left/Right arrows.
- Same bug affects Ctrl+Shift+Arrows, additionally with left arrow it does not select the previous word, only the current one.
- When using Ctrl+Right arrow caret disappears at the end of the text. When not using any modifier keys caret disappears both at the beginning and at the end.

**Comment by Mikanoshi** [comment]
4.2.6.8
- Enter any text, select it all and remove using Backspace/Delete - resulting plaintext will have 2 empty lines instead of 1. Same happens if you just press Backspace in empty plaintext.

**Comment by Mikanoshi** [comment]
4.2.6.10:
- `$(plaintext).state.focus = true` stopped working
